### get all players
GET http://localhost:3000/players/

### get player
GET http://localhost:3000/players/2/

### update player
PUT http://localhost:3000/players/2/

Content-Type: application/json

{
     "playerName": "Rama"
}

### get match details
GET http://localhost:3000/matches/18/

### get player matches 
GET http://localhost:3000/players/1/matches/

### get players in specific match 
GET http://localhost:3000/matches/10/players/

### get player statistics
GET http://localhost:3000/players/1/playerScores/